language: node_js
node_js:
  - "6"

before_install:
  - npm -g install node-gyp@3.4.0 node-pre-gyp@0.6.32

before_deploy:
  - npm run-script predeploy
  - LAST_COMMIT=$(git log -1 --pretty=format:'%h <%an> - %s')
  - echo "Deploying changes from $LAST_COMMIT"
  - node_modules/gh-pages/bin/gh-pages -d dist/ -m "Updates from $LAST_COMMIT"

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master