language: node_js
node_js:
  - "6"

cache:
  directories:
    - "node_modules"

after_success:
  - npm run build

before_deploy:
  - echo mauriciovieira.net > dist/CNAME

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master